# Generated by Django 4.2 on 2024-09-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_contact_email_post_location_post_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
